#!/bin/bash

if [ "$#" -lt "1" ]; then
	echo "usage: livecg <class name>"
	exit 1
fi

# find java claspath
DIR=`dirname $0`
#echo "we are operating from: $DIR"
CLASSPATH=.
CLASSPATH+=:$DIR/../lib/*
CLASSPATH+=:$DIR/../lib/batik/*
CLASSPATH+=:$DIR/../bin/main/
CLASSPATH+=:$DIR/../bin/test/
CLASSPATH+=:$DIR/../
#echo "CLASSPATH=$CLASSPATH"

CMD="java -cp $CLASSPATH"
exec $CMD "$@"
