./scripts/livecg-create-image -input res/presets/polygons/Big.geom -output geometry.png -output_format png -visualization geometry
./scripts/livecg-create-image -input res/presets/polygons/Big.geom -output dcel.png -output_format png -visualization dcel
./scripts/livecg-create-image -input res/presets/polygons/Big.geom -output monotone.png -output_format png -visualization monotone
./scripts/livecg-create-image -input res/presets/polygons/Big.geom -output triangulation.png -output_format png -visualization triangulation
./scripts/livecg-create-image -input res/presets/polygons/Big.geom -output spip.png -output_format png -visualization spip
./scripts/livecg-create-image -input res/presets/chan/Chan1.geom -output chan.png -output_format png -visualization chan
./scripts/livecg-create-image -input res/presets/voronoi/Points1.geom -output fortune.png -output_format png -visualization fortune
./scripts/livecg-create-image -input res/presets/frechet/Paper.geom -output freespace.png -output_format png -visualization freespace
./scripts/livecg-create-image -input res/presets/frechet/Paper.geom -output terrain.png -output_format png -visualization distanceterrain
